Vagrant.configure(2) do |config|
  config.vm.box = "debian-8.7.1-amd64.box"
  config.vm.provision "shell", inline: <<-SHELL
    sudo update-locale LANG=C.UTF-8
    # Already configured in /etc/sudoers.d/99_vagrant
    # sudo sh -c "echo '${USER} ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/nopasswd" && sudo chmod 0440 /etc/sudoers.d/nopasswd

    # https://docs.docker.com/engine/installation/linux/debian/
    sudo apt-get install -y apt-transport-https ca-certificates
    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    sudo sh -c "echo 'deb https://apt.dockerproject.org/repo debian-jessie main' > /etc/apt/sources.list.d/docker.list"
    sudo apt-get update
    sudo apt-cache policy docker-engine
    sudo apt-get install -y docker-engine
    sudo service docker start
  SHELL
end
