Vagrant.configure(2) do |config|
  config.vm.box = "packer_virtualbox-iso_virtualbox.box"
  config.vm.provision "shell", inline: <<-SHELL
    sudo sh -c "echo 'deb http://ftp.jp.debian.org/debian sid main' > /etc/apt/sources.list.d/sid.list"
    sudo apt-get update
    sudo apt-get install -y docker.io
  SHELL
end
