Vagrant.configure(2) do |config|
  config.vm.box = "debian-8.4.0-amd64.box"
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo update-locale LANG=C.UTF-8
    sudo apt-get update
    sudo apt-get install -y curl git
    curl -O https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb && rm erlang-solutions_1.0_all.deb
    sudo apt-get update
    sudo apt-get install -y erlang-dev erlang-eunit elixir
  SHELL
end
