Vagrant.configure(2) do |config|
  config.vm.box = "debian-8.0.0-amd64.box"
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo update-locale LANG=C.UTF-8
    sudo apt-get update
    sudo apt-get install -y curl git build-essential libncurses-dev libssl-dev unzip
    test -e ~/.asdf || git clone https://github.com/HashNuke/asdf.git ~/.asdf
    grep "source ~/.asdf/asdf.sh" ~/.bashrc > /dev/null 2>&1 || echo "source ~/.asdf/asdf.sh" >> ~/.bashrc

    ~/.asdf/bin/asdf plugin-update erlang || ~/.asdf/bin/asdf plugin-add erlang https://github.com/HashNuke/asdf-erlang.git
    ~/.asdf/bin/asdf install erlang 18.0
    grep erlang ~/.tool-versions > /dev/null 2>&1 || echo "erlang 18.0" >> ~/.tool-versions

    ~/.asdf/bin/asdf plugin-update elixir || ~/.asdf/bin/asdf plugin-add elixir https://github.com/HashNuke/asdf-elixir.git
    ~/.asdf/bin/asdf install elixir 1.0.4
    grep elixir ~/.tool-versions > /dev/null 2>&1 || echo "elixir 1.0.4" >> ~/.tool-versions
  SHELL
end
